# Generated by Django 4.1.4 on 2023-03-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentinformation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_age',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_result',
        ),
    ]
