# Generated by Django 4.1.4 on 2023-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinformation', '0002_remove_studentmodel_registration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('age_of_kid', models.CharField(max_length=100)),
                ('total_seat', models.CharField(max_length=100)),
                ('class_time', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
            ],
        ),
    ]
