# Generated by Django 4.1.4 on 2023-03-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinformation', '0003_kidclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidclasses',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
