# Generated by Django 4.1.4 on 2023-03-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinformation', '0005_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_subject', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
