# Generated by Django 4.1.4 on 2023-03-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinformation', '0006_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_school',
            field=models.CharField(max_length=100),
        ),
    ]
